[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
senddit_data_logics = "Fb5SwfkQxvcdRyXAc7BKm23irSR5A82vq1Gn1439W9ys"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
